# int3 specific test environment configuration
country:
  short:
    code: int3
  display:
    name: int3

# Country-specific deployment
sporty:
  deployment:
    available-countries: int3

# Country-specific URLs
sportyGlobal:
  api:
    url: https://sporty-global-int3.uat.sportybet2.com

# int3 specific settings
sporty_bet:
  country_code: int3

# int3 specific payment providers for UAT
payment:
  providers:
    testprovider:
      enabled: true
      test-mode: true
    
  gateway:
    url: https://payment-gateway-int3.uat.sportybet2.com