# int1 specific test environment configuration
country:
  short:
    code: int1
  display:
    name: int1

# Country-specific deployment
sporty:
  deployment:
    available-countries: int1

# Country-specific URLs
sportyGlobal:
  api:
    url: https://sporty-global-int1.uat.sportybet2.com

# int1 specific settings
sporty_bet:
  country_code: int1

# int1 specific payment providers for UAT
payment:
  providers:
    testprovider:
      enabled: true
      test-mode: true
    
  gateway:
    url: https://payment-gateway-int1.uat.sportybet2.com